#!/bin/bash

PNAME="$1"
LOG_FILE="$2"

./277087 &

for i in $(seq 0 1 20)
do
    # echo "$(date) :: $PNAME[$(pidof ${PNAME})] $(iotop -k -t -p $(pidof ${PNAME}) | tail -1)%" >> $LOG_FILE
    iostat -x sda -c 0.1 -t > stats.log

python3 draw_io_plot.py "$2"

pid=$(pidof 277087)
kill $pid
./clear